steps:
  # Étape 1 : Installer les dépendances pour les Cloud Functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'Fonctions/'

  # Étape 2 : Déployer les Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'createSpigotServer', '--runtime', 'nodejs20', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'createSpigotServer', '--region', 'europe-west1', '--memory', '256MB']
    dir: 'Fonctions/'

  # Étape 3 : Initialiser et Appliquer Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    args: [
        'apply',
        '-auto-approve',
        '-var=team_name=$_TEAM_NAME',
        '-var=player1=$_PLAYER1',
        '-var=player2=$_PLAYER2',
        '-var=player3=$_PLAYER3',
        '-var=player4=$_PLAYER4'
    ]
    dir: 'terraform'
    env:
      - 'GOOGLE_CREDENTIALS=$$GCP_SA_KEY'

  # Étape 4 : Déployer le script Google Apps
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['apps', 'deploy', '--project', 'glowing-road-451209-k6']
    dir: 'scripts'

# Définir les substitutions pour les variables d'environnement
substitutions:
  _TEAM_NAME: ''  # Remplacez par le nom de l'équipe
  _PLAYER1: ''    # Remplacez par le nom du joueur 1
  _PLAYER2: ''    # Remplacez par le nom du joueur 2
  _PLAYER3: ''    # Remplacez par le nom du joueur 3
  _PLAYER4: ''    # Remplacez par le nom du joueur 4
  _GCP_SA_KEY: 'YOUR_SERVICE_ACCOUNT_KEY'  # Remplacez par votre clé de compte de service

# Définir les images à construire (optionnel)
images:
  - 'gcr.io/$PROJECT_ID/your-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY
