steps:
  # Étape 1 : Installer les dépendances pour les Cloud Functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'Fonctions/'

  # Étape 2 : Déployer les Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'createSpigotServer', '--runtime', 'nodejs20', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'createSpigotServer', '--region', 'europe-west1', '--memory', '256MB']
    dir: 'Fonctions/'

  # Étape 3 : Initialiser Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
  - name: 'hashicorp/terraform:latest'
    args: [
        'apply',
        '-auto-approve',
        '-var=team_name=$TEAM_NAME',
        '-var=player1=$PLAYER1',
        '-var=player2=$PLAYER2',
        '-var=player3=$PLAYER3',
        '-var=player4=$PLAYER4'
    ]
    dir: 'terraform'

  # Étape 4 : Appliquer la configuration Terraform avec la variable
  - name: 'hashicorp/terraform:latest'
    args: ['apply','-auto-approve']
    dir: 'terraform'
    env:
      - 'GOOGLE_CREDENTIALS=$$GCP_SA_KEY'

  # Étape 5 : Déployer le script Google Apps
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['apps', 'deploy', '--project', 'glowing-road-451209-k6']
    dir: 'scripts'

# Définir les substitutions pour les variables d'environnement
substitutions: 

  _TEAM_NAME: ''
  _PLAYER1: ''
  _PLAYER2: ''
  _PLAYER3: ''
  _PLAYER4: ''
  _GCP_SA_KEY: 'YOUR_SERVICE_ACCOUNT_KEY'

# Définir les images à construire (optionnel)
images:
  - 'gcr.io/$PROJECT_ID/your-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY